name: Test
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - run: npm run build
             

