name: Manual Trigger Workflow

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
